export enum BotEvents {
    NONE = "NONE",
    NIGHTCLUBS_DONE = "NIGHTCLUBS_DONE",
    ENTER_NIGHTCLUB_DONE = "ENTER_NIGHTCLUB_DONE",
    HOSPITAL_DONE = "HOSPITAL_DONE",
    DETOX_DONE = "DETOX_DONE",
    VISITORS_DONE = "VISITORS_DONE",
    EXIT_NIGHTCLUB_DONE = "EXIT_NIGHTCLUB_DONE",
    BUY_DRUG_OR_HOOKER_DONE = "BUY_DRUG_DONE",
    ROBBERIES_DONE = "ROBBERIES_DONE",
    HOOKERS_DONE = "HOOKERS_DONE",
    ROB_DONE = "ROB_DONE",
    ACCEPT_GANG_ROBBERY_DONE = "ACCEPT_GANG_ROBBERY_DONE",
    EXECUTE_GANG_ROBBERY_DONE = "EXECUTE_GANG_ROBBERY_DONE"

}